FROM python:3.13.11

WORKDIR /app

# Install packages requied to interact with PostgreSQL and MinIO
RUN pip install psycopg2 boto3
# Install the dev version of mlflow via wheel
COPY dist ./dist
RUN pip install dist/mlflow-*.whl
